---
driver:
  name: vagrant

provisioner:
  omnibus_cachier: true
  require_chef: false
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  dependencies:
    - name: sun-java
      repo: git
      source: https://github.com/saltstack-formulas/sun-java-formula.git
  formula: elasticsearch
  pillars:
  state_top:
    base:
      '*':
        - sun-java
        - sun-java.env
        - elasticsearch

platforms:
  - name: ubuntu-16.04
    driver_config:
      provision_command:
        - apt-get install git locales -y
        - locale-gen en_US.UTF-8

suites:
  - name: elasticsearch-single
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - elasticsearch
        elasticsearch.sls:
          elasticsearch:
            version: "5.4.3"
            plugins:
              lang-python: lang-python
            jvm_opts:
              - '# Test String'
            systemd:
              Service:
                '# Test': String


verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE
